biynlvp_homepage:
    path:     /
    defaults: { _controller: biynlvpBundle:Default:index }
    
# ROUTE MEMBRES

biynlvp_espacemembres:
    path:     /membre/
    defaults: { _controller: biynlvpBundle:Membre:accueil }

# ROUTE ADMINISTRATION

biynlvp_admin_membres:
    path:     /admin/membres
    defaults: { _controller: biynlvpBundle:Admin:membres }

# AUTHENTIFICATION

biynlvp_connexion:
    path:     /membre/connexion
    defaults: { _controller: biynMembreBundle:Security:login }

biynlvp_connexion_validation:
    path:     /membre/connexion_validation

biynlvp_deconnexion:
    path:     /membre/deconnexion
    
biynlvp_inscription:
    path:     /membre/inscription
    defaults: { _controller: biynlvpBundle:Membre:inscription }