# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        biyn\lvpBundle\Entity\Membres: plaintext

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_MEMBRE

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
        #    memory:
        #        users:
        #            membre@test.fr:  { password: userpass, roles: [ 'ROLE_MEMBRE' ] }
        #            admin@test.fr: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class:    biyn\lvpBundle\Entity\Membres
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/ 
            anonymous: ~
            # activate different ways to authenticate
            provider: main

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: biynlvp_connexion
                check_path: biynlvp_connexion_validation
                default_target_path: biynlvp_espacemembres
                # always_use_default_target_path: true
            logout:
                path:       biynlvp_deconnexion
                target:     biynlvp_homepage